#!/usr/bin/env node
// Converts the Figma image fills used by the built frames into right-sized WebP files.
//
//   node scripts/optimize-images.mjs [--force]
//
// Reads design/file.json + design/figma-src/*, writes public/img/<ref8>.webp and
// src/data/images.generated.ts (short ref → { src, width, height }).
// Target width = largest rendered size of that image across the site × 2 (retina), capped at 2880.

import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { FRAMES } from "./frames.mjs";
import { renderedSize } from "./lib.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SRC = join(ROOT, "design", "figma-src");
const OUT = join(ROOT, "public", "img");
const force = process.argv.includes("--force");
mkdirSync(OUT, { recursive: true });

const doc = JSON.parse(readFileSync(join(ROOT, "design", "file.json"), "utf8"));
const byId = new Map();
(function index(n) { byId.set(n.id, n); n.children?.forEach(index); })(doc.document);

// ref → largest box it is drawn into
const uses = new Map();
const walk = (n) => {
  if (n.visible === false) return;
  for (const f of n.fills ?? []) {
    if (f.type !== "IMAGE" || f.visible === false || !f.imageRef) continue;
    if (!n.absoluteBoundingBox) continue;
    const b = renderedSize(n);
    const u = uses.get(f.imageRef) ?? { w: 0, h: 0 };
    uses.set(f.imageRef, { w: Math.max(u.w, b.w), h: Math.max(u.h, b.h) });
  }
  n.children?.forEach(walk);
};
for (const id of FRAMES) {
  if (byId.has(id)) walk(byId.get(id));
  else console.warn(`missing frame ${id}`);
}

const files = new Map(readdirSync(SRC).map((f) => [f.split(".")[0], f]));
const manifest = {};
let written = 0, bytes = 0;
for (const [ref, box] of uses) {
  const file = files.get(ref);
  if (!file) { console.warn(`no source for ${ref}`); continue; }
  const key = ref.slice(0, 8);
  if (manifest[key]) throw new Error(`short ref collision ${key}`);
  const out = join(OUT, `${key}.webp`);
  const input = join(SRC, file);
  const meta = await sharp(input).metadata();
  // Cover-fit: the image may need to be wider than the box if aspect ratios differ.
  const aspect = meta.width / meta.height;
  const needed = Math.ceil(Math.max(box.w, box.h * aspect) * 2);
  const width = Math.min(meta.width, needed, 2880);
  if (force || !existsSync(out)) {
    const alpha = meta.hasAlpha;
    await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: alpha ? 90 : 78, alphaQuality: 90 }).toFile(out);
    written++;
  }
  const outMeta = await sharp(out).metadata();
  bytes += (await sharp(out).toBuffer()).length;
  manifest[key] = { src: `/img/${key}.webp`, width: outMeta.width, height: outMeta.height };
}

const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
writeFileSync(
  join(ROOT, "src", "data", "images.generated.ts"),
  `// Generated by scripts/optimize-images.mjs — do not edit.\n` +
    `export const figmaImages = ${JSON.stringify(sorted, null, 2)} as const satisfies Record<string, { src: string; width: number; height: number }>;\n`,
);
console.log(`${uses.size} refs used, ${written} written, total ${(bytes / 1e6).toFixed(1)} MB`);
