// Generated by scripts/optimize-images.mjs — do not edit.
export const figmaImages = {
  "71328574": {
    "src": "/img/71328574.webp",
    "width": 748,
    "height": 1122
  },
  "0129d864": {
    "src": "/img/0129d864.webp",
    "width": 2880,
    "height": 1920
  },
  "02195641": {
    "src": "/img/02195641.webp",
    "width": 1280,
    "height": 853
  },
  "028cd2d4": {
    "src": "/img/028cd2d4.webp",
    "width": 770,
    "height": 777
  },
  "0314b44c": {
    "src": "/img/0314b44c.webp",
    "width": 2731,
    "height": 4096
  },
  "055a6eaa": {
    "src": "/img/055a6eaa.webp",
    "width": 1281,
    "height": 854
  },
  "0c120a38": {
    "src": "/img/0c120a38.webp",
    "width": 746,
    "height": 1119
  },
  "0ce9ce62": {
    "src": "/img/0ce9ce62.webp",
    "width": 1290,
    "height": 1720
  },
  "0d0b2823": {
    "src": "/img/0d0b2823.webp",
    "width": 1979,
    "height": 2968
  },
  "0d9f823b": {
    "src": "/img/0d9f823b.webp",
    "width": 2560,
    "height": 3200
  },
  "0fa14d84": {
    "src": "/img/0fa14d84.webp",
    "width": 1290,
    "height": 1143
  },
  "12b98ad8": {
    "src": "/img/12b98ad8.webp",
    "width": 810,
    "height": 1438
  },
  "140f8830": {
    "src": "/img/140f8830.webp",
    "width": 2880,
    "height": 1920
  },
  "15296f32": {
    "src": "/img/15296f32.webp",
    "width": 258,
    "height": 145
  },
  "21e80b3e": {
    "src": "/img/21e80b3e.webp",
    "width": 1268,
    "height": 1902
  },
  "225c4b5b": {
    "src": "/img/225c4b5b.webp",
    "width": 2211,
    "height": 1474
  },
  "248fc442": {
    "src": "/img/248fc442.webp",
    "width": 1080,
    "height": 1302
  },
  "26f7825b": {
    "src": "/img/26f7825b.webp",
    "width": 1170,
    "height": 1688
  },
  "2a4263d3": {
    "src": "/img/2a4263d3.webp",
    "width": 1315,
    "height": 1676
  },
  "2afdf3e3": {
    "src": "/img/2afdf3e3.webp",
    "width": 60,
    "height": 60
  },
  "2c2eb92b": {
    "src": "/img/2c2eb92b.webp",
    "width": 54,
    "height": 54
  },
  "2cd9ebcd": {
    "src": "/img/2cd9ebcd.webp",
    "width": 2880,
    "height": 3840
  },
  "307366d1": {
    "src": "/img/307366d1.webp",
    "width": 581,
    "height": 872
  },
  "31c8ae86": {
    "src": "/img/31c8ae86.webp",
    "width": 815,
    "height": 1222
  },
  "32db8325": {
    "src": "/img/32db8325.webp",
    "width": 746,
    "height": 1119
  },
  "34023d2c": {
    "src": "/img/34023d2c.webp",
    "width": 1040,
    "height": 693
  },
  "35a86612": {
    "src": "/img/35a86612.webp",
    "width": 1080,
    "height": 1080
  },
  "375ae365": {
    "src": "/img/375ae365.webp",
    "width": 1209,
    "height": 1813
  },
  "38a27357": {
    "src": "/img/38a27357.webp",
    "width": 600,
    "height": 600
  },
  "3c94fb25": {
    "src": "/img/3c94fb25.webp",
    "width": 1662,
    "height": 2494
  },
  "3f8913e9": {
    "src": "/img/3f8913e9.webp",
    "width": 760,
    "height": 515
  },
  "3fa8e614": {
    "src": "/img/3fa8e614.webp",
    "width": 1414,
    "height": 2121
  },
  "44e5f035": {
    "src": "/img/44e5f035.webp",
    "width": 600,
    "height": 600
  },
  "469b1d65": {
    "src": "/img/469b1d65.webp",
    "width": 906,
    "height": 1358
  },
  "485f901c": {
    "src": "/img/485f901c.webp",
    "width": 2880,
    "height": 1920
  },
  "4a7a02bd": {
    "src": "/img/4a7a02bd.webp",
    "width": 47,
    "height": 47
  },
  "530d7ab8": {
    "src": "/img/530d7ab8.webp",
    "width": 2880,
    "height": 2160
  },
  "533514a0": {
    "src": "/img/533514a0.webp",
    "width": 1603,
    "height": 2404
  },
  "53d77f3d": {
    "src": "/img/53d77f3d.webp",
    "width": 2735,
    "height": 4096
  },
  "54274e9a": {
    "src": "/img/54274e9a.webp",
    "width": 1023,
    "height": 987
  },
  "55924d82": {
    "src": "/img/55924d82.webp",
    "width": 640,
    "height": 768
  },
  "58c33a2e": {
    "src": "/img/58c33a2e.webp",
    "width": 1298,
    "height": 1947
  },
  "5b5b419c": {
    "src": "/img/5b5b419c.webp",
    "width": 683,
    "height": 1024
  },
  "5cdfd365": {
    "src": "/img/5cdfd365.webp",
    "width": 2880,
    "height": 1920
  },
  "5daf1c9d": {
    "src": "/img/5daf1c9d.webp",
    "width": 632,
    "height": 632
  },
  "5dba371d": {
    "src": "/img/5dba371d.webp",
    "width": 256,
    "height": 320
  },
  "6084eba3": {
    "src": "/img/6084eba3.webp",
    "width": 480,
    "height": 480
  },
  "61c2f7f1": {
    "src": "/img/61c2f7f1.webp",
    "width": 590,
    "height": 786
  },
  "66056fdb": {
    "src": "/img/66056fdb.webp",
    "width": 2761,
    "height": 2199
  },
  "674c4e25": {
    "src": "/img/674c4e25.webp",
    "width": 182,
    "height": 182
  },
  "688c437e": {
    "src": "/img/688c437e.webp",
    "width": 1483,
    "height": 1483
  },
  "6912ba66": {
    "src": "/img/6912ba66.webp",
    "width": 788,
    "height": 1182
  },
  "6960ecc4": {
    "src": "/img/6960ecc4.webp",
    "width": 650,
    "height": 650
  },
  "6c1f024e": {
    "src": "/img/6c1f024e.webp",
    "width": 2880,
    "height": 3846
  },
  "6dc1ee7b": {
    "src": "/img/6dc1ee7b.webp",
    "width": 600,
    "height": 599
  },
  "6f5ac309": {
    "src": "/img/6f5ac309.webp",
    "width": 2010,
    "height": 2443
  },
  "7075b5a8": {
    "src": "/img/7075b5a8.webp",
    "width": 400,
    "height": 600
  },
  "744e0df6": {
    "src": "/img/744e0df6.webp",
    "width": 614,
    "height": 1092
  },
  "74e2c248": {
    "src": "/img/74e2c248.webp",
    "width": 1020,
    "height": 1360
  },
  "7623854c": {
    "src": "/img/7623854c.webp",
    "width": 1060,
    "height": 1588
  },
  "7747786d": {
    "src": "/img/7747786d.webp",
    "width": 1666,
    "height": 2504
  },
  "7b84c1d5": {
    "src": "/img/7b84c1d5.webp",
    "width": 1155,
    "height": 1732
  },
  "84ad8815": {
    "src": "/img/84ad8815.webp",
    "width": 258,
    "height": 145
  },
  "869fa8c0": {
    "src": "/img/869fa8c0.webp",
    "width": 2880,
    "height": 3516
  },
  "8ba31dce": {
    "src": "/img/8ba31dce.webp",
    "width": 1170,
    "height": 609
  },
  "8bf340b5": {
    "src": "/img/8bf340b5.webp",
    "width": 813,
    "height": 1446
  },
  "8c36aed6": {
    "src": "/img/8c36aed6.webp",
    "width": 418,
    "height": 628
  },
  "906e1600": {
    "src": "/img/906e1600.webp",
    "width": 2880,
    "height": 1920
  },
  "90fa0e91": {
    "src": "/img/90fa0e91.webp",
    "width": 1602,
    "height": 1068
  },
  "91460a2c": {
    "src": "/img/91460a2c.webp",
    "width": 578,
    "height": 578
  },
  "91b86802": {
    "src": "/img/91b86802.webp",
    "width": 1262,
    "height": 1681
  },
  "93f205e2": {
    "src": "/img/93f205e2.webp",
    "width": 2880,
    "height": 3600
  },
  "978bbae5": {
    "src": "/img/978bbae5.webp",
    "width": 747,
    "height": 498
  },
  "9a76bf0c": {
    "src": "/img/9a76bf0c.webp",
    "width": 2731,
    "height": 4096
  },
  "9f86a369": {
    "src": "/img/9f86a369.webp",
    "width": 200,
    "height": 200
  },
  "a00ee884": {
    "src": "/img/a00ee884.webp",
    "width": 2731,
    "height": 4096
  },
  "a4de24e5": {
    "src": "/img/a4de24e5.webp",
    "width": 284,
    "height": 284
  },
  "a63bfe4f": {
    "src": "/img/a63bfe4f.webp",
    "width": 2667,
    "height": 4000
  },
  "a6a23db1": {
    "src": "/img/a6a23db1.webp",
    "width": 2880,
    "height": 1920
  },
  "a6fb7778": {
    "src": "/img/a6fb7778.webp",
    "width": 100,
    "height": 50
  },
  "a760c026": {
    "src": "/img/a760c026.webp",
    "width": 1701,
    "height": 1134
  },
  "aaedc617": {
    "src": "/img/aaedc617.webp",
    "width": 1518,
    "height": 1012
  },
  "ab3dfd53": {
    "src": "/img/ab3dfd53.webp",
    "width": 480,
    "height": 480
  },
  "ac44e94a": {
    "src": "/img/ac44e94a.webp",
    "width": 813,
    "height": 1445
  },
  "ac665278": {
    "src": "/img/ac665278.webp",
    "width": 1159,
    "height": 1738
  },
  "af0f7990": {
    "src": "/img/af0f7990.webp",
    "width": 151,
    "height": 71
  },
  "b345eaa4": {
    "src": "/img/b345eaa4.webp",
    "width": 716,
    "height": 403
  },
  "bbec44a4": {
    "src": "/img/bbec44a4.webp",
    "width": 1118,
    "height": 1397
  },
  "bd75cc4d": {
    "src": "/img/bd75cc4d.webp",
    "width": 2880,
    "height": 1920
  },
  "becff19f": {
    "src": "/img/becff19f.webp",
    "width": 2470,
    "height": 3705
  },
  "befa71af": {
    "src": "/img/befa71af.webp",
    "width": 43,
    "height": 43
  },
  "c28d22a1": {
    "src": "/img/c28d22a1.webp",
    "width": 601,
    "height": 902
  },
  "cbb59c48": {
    "src": "/img/cbb59c48.webp",
    "width": 907,
    "height": 1361
  },
  "cc4424a4": {
    "src": "/img/cc4424a4.webp",
    "width": 814,
    "height": 1221
  },
  "d51ee882": {
    "src": "/img/d51ee882.webp",
    "width": 2304,
    "height": 4096
  },
  "dbded33e": {
    "src": "/img/dbded33e.webp",
    "width": 924,
    "height": 1386
  },
  "df48dae6": {
    "src": "/img/df48dae6.webp",
    "width": 811,
    "height": 1453
  },
  "df6c08b4": {
    "src": "/img/df6c08b4.webp",
    "width": 811,
    "height": 1217
  },
  "e4bee458": {
    "src": "/img/e4bee458.webp",
    "width": 615,
    "height": 923
  },
  "e4da1a2d": {
    "src": "/img/e4da1a2d.webp",
    "width": 1261,
    "height": 1891
  },
  "e4eac00a": {
    "src": "/img/e4eac00a.webp",
    "width": 1572,
    "height": 1048
  },
  "e507eee8": {
    "src": "/img/e507eee8.webp",
    "width": 320,
    "height": 312
  },
  "e71a23c7": {
    "src": "/img/e71a23c7.webp",
    "width": 811,
    "height": 1217
  },
  "e7ddb6a3": {
    "src": "/img/e7ddb6a3.webp",
    "width": 712,
    "height": 883
  },
  "e943f214": {
    "src": "/img/e943f214.webp",
    "width": 2481,
    "height": 3721
  },
  "e967b782": {
    "src": "/img/e967b782.webp",
    "width": 800,
    "height": 903
  },
  "eb07e6b7": {
    "src": "/img/eb07e6b7.webp",
    "width": 582,
    "height": 388
  },
  "ebdd0bf0": {
    "src": "/img/ebdd0bf0.webp",
    "width": 1536,
    "height": 1024
  },
  "ec6a15c1": {
    "src": "/img/ec6a15c1.webp",
    "width": 714,
    "height": 1269
  },
  "ee423c71": {
    "src": "/img/ee423c71.webp",
    "width": 974,
    "height": 1325
  },
  "f16c3a1c": {
    "src": "/img/f16c3a1c.webp",
    "width": 278,
    "height": 42
  },
  "f365754f": {
    "src": "/img/f365754f.webp",
    "width": 2880,
    "height": 1920
  },
  "f5bbbacc": {
    "src": "/img/f5bbbacc.webp",
    "width": 1297,
    "height": 1945
  },
  "f650e66a": {
    "src": "/img/f650e66a.webp",
    "width": 832,
    "height": 832
  },
  "f6c095f9": {
    "src": "/img/f6c095f9.webp",
    "width": 2880,
    "height": 3594
  },
  "fb4c92a4": {
    "src": "/img/fb4c92a4.webp",
    "width": 600,
    "height": 600
  },
  "fd30324e": {
    "src": "/img/fd30324e.webp",
    "width": 145,
    "height": 104
  },
  "fd3e0c82": {
    "src": "/img/fd3e0c82.webp",
    "width": 1126,
    "height": 750
  },
  "fe2d24f5": {
    "src": "/img/fe2d24f5.webp",
    "width": 2458,
    "height": 1639
  },
  "fe2df40c": {
    "src": "/img/fe2df40c.webp",
    "width": 2731,
    "height": 4096
  },
  "fe88e2e2": {
    "src": "/img/fe88e2e2.webp",
    "width": 2731,
    "height": 4096
  },
  "fec84810": {
    "src": "/img/fec84810.webp",
    "width": 2880,
    "height": 2160
  }
} as const satisfies Record<string, { src: string; width: number; height: number }>;
